### ISSUE TITLE
Allow to overrule splunkdb path

### ISSUE THREAD

**Issue by msnellen** [cudgel/splunk#22]
We normally install splunk in the normal location (/opt/splunk) but for indexers we prefer to have the data stored outside of this location on a separate disk/partition. Unfortunately I don't see an option to overrule the default /opt/splunk/var/lib/splunk location without moving everything to a different place.
Now I either have to mount the LVM module as /opt/splunk/var/lib/splunk or I need to resort to symlinks.

**Comment by cudgel** [comment]
Hi, it may not be covered in the existing documentation, but there are three parameters that control this:

```
splunk::warm_path
splunk::cold_path
splunk::datamodel_path
```

Additionally, if you are using SmartStore, you can specify splunk::remote_path and `splunk::cold_path` has no effect. 

Please let me know if this answers your question.
